/-!
# One-generated (1518 + 3862)-magmas are trivial or the Z/3 shift

Laws are numbered as in the Equational Theories Project (ETP, `teorth/equational_theories`): a law is an identity between
two words in a binary operation `◇`, and a magma satisfies it when the identity holds for all values of the variables.
Write `S x = x ◇ x`.

**Theorem A.** In every magma satisfying laws 1518 (`x = (y ◇ y) ◇ (x ◇ (y ◇ x))`) and 3862 (`x ◇ x = (x ◇ (x ◇ x)) ◇ x`),
for every `x` and all `u, v` in `T = {x, S x, S (S x)}` one has `u ◇ v = S v`, and `S (S (S x)) = x`.  Hence every word
in `x` lies in `T`, and `T` has one element or three distinct elements on which `◇` is the cyclic shift `u ◇ v = S v`.
So every one-generated magma satisfying 1518 and 3862 is the trivial magma or the Z/3 shift `x ◇ y = y + 1`.
No finiteness is assumed.
Declarations `table`, `cube`, `words_in_T`, `one_or_three`.

**Where the statement comes from.** Terence Tao conjectured it on the Lean Zulip (Equational stream, "Austin pairs",
2024-11-29, message 485148288), for magmas satisfying 1518 together with all four of 47, 614, 817 and 3862.  That message
carried no finiteness hypothesis.  Assuming 3862 alone is no weaker rather than stronger: Matthew Bolan reported the same
day (message 485153888) that 1518 and 3862 already imply the other three targets.  What is added here is a proof.  The
ETP sources, the Lean Zulip Equational stream, the SAIR Zulip, arXiv and the Palomar registry were searched (September
2026) without finding one; the result may be folklore.

**Why the classification was wanted.** In that thread the one-generated models of 1518 are the candidate *base* models for
the cohomological construction of countermodels, which is why Tao asked for them: with the classification, a
constant-coefficient abelian extension of a finite 1518-magma can violate 47, 614, 817 or 3862 only if its base already
does, so the construction cannot settle those four implications from any finite base.  That consequence is proved in the
repository in prose from kernel-checked certificate identities; it is not stated in this Challenge, and neither is the
explicit family of finite 1518-magmas that does refute the four targets with base-dependent coefficients.

The definitions below are the ordinary ones.  Proofs are in `Solution.lean`, which restates each declaration and proves it
from `lean/OneGenerated1518.lean`, a transcription of equational proofs found by Vampire 5.1.0.
-/

namespace Magma1518

/-- ETP law 1518: `x = (y ◇ y) ◇ (x ◇ (y ◇ x))`. -/
def Law1518 {G : Type} (op : G → G → G) : Prop := ∀ x y, x = (op (op y y) (op x (op y x)))

/-- ETP law 3862: `x ◇ x = (x ◇ (x ◇ x)) ◇ x`. -/
def Law3862 {G : Type} (op : G → G → G) : Prop := ∀ x, (op x x) = (op (op x (op x x)) x)

/-- ETP law 47: `x = x ◇ (x ◇ (x ◇ x))`. -/
def Law47 {G : Type} (op : G → G → G) : Prop := ∀ x, x = (op x (op x (op x x)))

/-- ETP law 614: `x = x ◇ (x ◇ ((x ◇ x) ◇ x))`. -/
def Law614 {G : Type} (op : G → G → G) : Prop := ∀ x, x = (op x (op x (op (op x x) x)))

/-- ETP law 817: `x = x ◇ ((x ◇ x) ◇ (x ◇ x))`. -/
def Law817 {G : Type} (op : G → G → G) : Prop := ∀ x, x = (op x (op (op x x) (op x x)))

/-- `T x = {x, S x, S (S x)}` with `S y = y ◇ y`: `inT op x y` says that `y` is one of the three. -/
def inT {G : Type} (op : G → G → G) (x y : G) : Prop := y = x ∨ y = op x x ∨ y = op (op x x) (op x x)

/-- Words in one generator: the free magma on one generator `v`. -/
inductive W where
  | v : W
  | m : W → W → W

/-- Evaluation of a word at `x`. -/
def ev {G : Type} (op : G → G → G) (x : G) : W → G
  | .v => x
  | .m a b => op (ev op x a) (ev op x b)

/-- Theorem A (table). In a magma satisfying 1518 and 3862, for every `x` and all `u, v ∈ {x, S x, S (S x)}`, `u ◇ v = S v = v ◇ v`. -/
theorem table {G : Type} (op : G → G → G) (h1 : Law1518 op) (h2 : Law3862 op) (x u v : G) (hu : inT op x u) (hv : inT op x v) :
    op u v = op v v := by
  sorry

/-- Theorem A, cyclicity: `S (S (S x)) = x`, i.e. `(S x ◇ S x) ◇ (S x ◇ S x) = x`. -/
theorem cube {G : Type} (op : G → G → G) (h1 : Law1518 op) (h2 : Law3862 op) (x : G) :
    op (op (op x x) (op x x)) (op (op x x) (op x x)) = x := by
  sorry

/-- Corollary A′: every word in `x` evaluates into `{x, S x, S (S x)}`, so the submagma generated by `x` is that set. -/
theorem words_in_T {G : Type} (op : G → G → G) (h1 : Law1518 op) (h2 : Law3862 op) (x : G) (w : W) :
    inT op x (ev op x w) := by
  sorry

/-- Corollary A′: either `S x = x = S (S x)` (one element) or `x, S x, S (S x)` are pairwise distinct (three elements). -/
theorem one_or_three {G : Type} (op : G → G → G) (h1 : Law1518 op) (h2 : Law3862 op) (x : G) :
    (op x x = x ∧ op (op x x) (op x x) = x) ∨
    (op x x ≠ x ∧ op (op x x) (op x x) ≠ x ∧ op (op x x) (op x x) ≠ op x x) := by
  sorry

end Magma1518
