import Std.Tactic.BVDecide
set_option maxRecDepth 100000
set_option maxHeartbeats 0
/-!
Census of one-generated 1518-magmas, size 2. Generated by research/audit/gen_census_lean.py.
Cells t_a_b : BitVec 3 encode the table (range hypotheses t_a_b < 2); law_x_y is
  x = (y ◇ y) ◇ (x ◇ (y ◇ x))  at the concrete pair (x, y), with the variable-index lookups written as muxes;
r_i_k : Bool means "k is reachable from the generator g in i rounds"; full says everything is reached in 1 rounds.
Trust: bv_decide bit-blasts, calls the bundled CaDiCaL, and checks the LRAT proof with Lean's verified checker run
natively; the check is recorded as an auxiliary axiom `…_native.bv_decide.ax_…` (the native_decide trust model).
-/
namespace Census1518

theorem no_one_generated_2 (t_0_0 t_0_1 t_1_0 t_1_1 g : BitVec 3) (r_0_0 r_0_1 r_1_0 r_1_1 : Bool)
    (range_0_0 : t_0_0 < 2#3)
    (range_0_1 : t_0_1 < 2#3)
    (range_1_0 : t_1_0 < 2#3)
    (range_1_1 : t_1_1 < 2#3)
    (range_g : g < 2#3)
    (law_0_0 : (bif t_0_0 == 0#3 then (bif (bif t_0_0 == 0#3 then t_0_0 else t_0_1) == 0#3 then t_0_0 else t_0_1) else (bif (bif t_0_0 == 0#3 then t_0_0 else t_0_1) == 0#3 then t_1_0 else t_1_1)) = 0#3)
    (law_0_1 : (bif t_1_1 == 0#3 then (bif (bif t_1_0 == 0#3 then t_0_0 else t_0_1) == 0#3 then t_0_0 else t_0_1) else (bif (bif t_1_0 == 0#3 then t_0_0 else t_0_1) == 0#3 then t_1_0 else t_1_1)) = 0#3)
    (law_1_0 : (bif t_0_0 == 0#3 then (bif (bif t_0_1 == 0#3 then t_1_0 else t_1_1) == 0#3 then t_0_0 else t_0_1) else (bif (bif t_0_1 == 0#3 then t_1_0 else t_1_1) == 0#3 then t_1_0 else t_1_1)) = 1#3)
    (law_1_1 : (bif t_1_1 == 0#3 then (bif (bif t_1_1 == 0#3 then t_1_0 else t_1_1) == 0#3 then t_0_0 else t_0_1) else (bif (bif t_1_1 == 0#3 then t_1_0 else t_1_1) == 0#3 then t_1_0 else t_1_1)) = 1#3)
    (reach_0_0 : r_0_0 = (g == 0#3))
    (reach_0_1 : r_0_1 = (g == 1#3))
    (reach_1_0 : r_1_0 = (r_0_0 || (((r_0_0 && r_0_0 && (t_0_0 == 0#3)) || (r_0_0 && r_0_1 && (t_0_1 == 0#3))) || ((r_0_1 && r_0_0 && (t_1_0 == 0#3)) || (r_0_1 && r_0_1 && (t_1_1 == 0#3))))))
    (reach_1_1 : r_1_1 = (r_0_1 || (((r_0_0 && r_0_0 && (t_0_0 == 1#3)) || (r_0_0 && r_0_1 && (t_0_1 == 1#3))) || ((r_0_1 && r_0_0 && (t_1_0 == 1#3)) || (r_0_1 && r_0_1 && (t_1_1 == 1#3))))))
    (full : (r_1_0 && r_1_1) = true) :
    False := by
  bv_decide (config := { timeout := 7000 })

theorem law_control_2_0 : 0#3 < 2#3 ∧ 1#3 < 2#3 ∧ 0#3 < 2#3 ∧ 1#3 < 2#3 ∧ (bif 0#3 == 0#3 then (bif (bif 0#3 == 0#3 then 0#3 else 1#3) == 0#3 then 0#3 else 1#3) else (bif (bif 0#3 == 0#3 then 0#3 else 1#3) == 0#3 then 0#3 else 1#3)) = 0#3 ∧ (bif 1#3 == 0#3 then (bif (bif 0#3 == 0#3 then 0#3 else 1#3) == 0#3 then 0#3 else 1#3) else (bif (bif 0#3 == 0#3 then 0#3 else 1#3) == 0#3 then 0#3 else 1#3)) = 0#3 ∧ (bif 0#3 == 0#3 then (bif (bif 1#3 == 0#3 then 0#3 else 1#3) == 0#3 then 0#3 else 1#3) else (bif (bif 1#3 == 0#3 then 0#3 else 1#3) == 0#3 then 0#3 else 1#3)) = 1#3 ∧ (bif 1#3 == 0#3 then (bif (bif 1#3 == 0#3 then 0#3 else 1#3) == 0#3 then 0#3 else 1#3) else (bif (bif 1#3 == 0#3 then 0#3 else 1#3) == 0#3 then 0#3 else 1#3)) = 1#3 := by
  decide

end Census1518
#print axioms Census1518.no_one_generated_2
#print axioms Census1518.law_control_2_0

