"""Kernel-`decide` Lean certificate that the F+ member of Theorem F over F_p (p = 1 mod 4, i = smallest square root of -1) is a
3p-element magma satisfying 1518 and violating 47, 614, 817, 3862, with squaring of order 12.  The table is encoded as one natural
number in base 3p (cell (a,b) is digit a*n+b), decoded by division, as in census_lean/CensusBridge.lean.  No axioms expected.
Usage: gen_family_lean.py <data> <p> <outfile>"""
import sys, json, re
from fractions import Fraction as Fr
S, p, out = sys.argv[1], int(sys.argv[2]), sys.argv[3]; n = 3*p
ip = next(v for v in range(1, p) if v*v % p == p-1)
fam = json.load(open(f"{S}/fifteen/family_Qi.json"))["F+"]
def val(s):
    s = s.replace(" ", "")
    if s.endswith("i"):
        core = s[:-1]; k = max(core.rfind("+", 1), core.rfind("-", 1))
        re_, im_ = (core[:k], core[k:]) if k > 0 else ("0", core)
        im_ = {"": "1", "+": "1", "-": "-1"}.get(im_, im_)
    else: re_, im_ = s, "0"
    r, m = Fr(re_), Fr(im_)
    return (r.numerator*pow(r.denominator, -1, p) + m.numerator*pow(m.denominator, -1, p)*ip) % p
a = [[val(v) for v in row] for row in fam["a"]]; b = [[val(v) for v in row] for row in fam["b"]]
T = [[0]*n for _ in range(n)]
for x in range(3):
    for s in range(p):
        for y in range(3):
            for t in range(p): T[p*x+s][p*y+t] = p*((y+1) % 3) + (a[x][y]*s + b[x][y]*t) % p
code = sum(T[u][v] * n**(u*n+v) for u in range(n) for v in range(n))
eq = open(f"{S}/etp/equations.txt").read().splitlines()
def parse(st):
    toks = re.findall(r"[a-z]|◇|\(|\)", st); pos = [0]
    def atom():
        t = toks[pos[0]]; pos[0] += 1
        if t == "(":
            e = expr(); pos[0] += 1; return e
        return t
    def expr():
        left = atom()
        while pos[0] < len(toks) and toks[pos[0]] == "◇": pos[0] += 1; left = (left, atom())
        return left
    return expr()
def lean(t): return t if isinstance(t, str) else f"(op {lean(t[0])} {lean(t[1])})"
def law(k):
    l, r = eq[k-1].split(" = "); vs = sorted(set(re.findall(r"[a-z]", eq[k-1])))
    return f"∀ {' '.join(vs)} : Fin {n}, {lean(parse(l))} = {lean(parse(r))}", eq[k-1]
s3 = "op (op (op x x) (op x x)) (op (op x x) (op x x))"   # S^3 x written out
lines = [f"/-! Theorem F, member over F_{p} (i = {ip}), {n} elements: 1518 holds, 47, 614, 817, 3862 fail, squaring has order 12.",
         f"    Generated by scripts/gen_family_lean.py from data/fifteen/family_Qi.json; a = {a}, b = {b} (mod {p}). Kernel `decide` only. -/",
         "set_option maxRecDepth 200000", "set_option maxHeartbeats 0", f"namespace FamilyF{p}",
         f"def n : Nat := {n}", f"def code : Nat := {code}",
         f"def op (a b : Fin {n}) : Fin {n} := ⟨(code / {n} ^ (a.val * {n} + b.val)) % {n}, Nat.mod_lt _ (by decide)⟩",
         f"def sq (x : Fin {n}) : Fin {n} := op x x"]
for k in (1518,):
    st, w = law(k); lines.append(f"/-- {w} -/\ntheorem law{k} : {st} := by decide")
for k in (47, 614, 817, 3862):
    st, w = law(k); lines.append(f"/-- fails: {w} -/\ntheorem not{k} : ¬ ({st}) := by decide")
lines.append(f"theorem sq_cubed_not_id : ¬ (∀ x : Fin {n}, sq (sq (sq x)) = x) := by decide")
lines.append(f"theorem sq_pow12_id : ∀ x : Fin {n}, sq (sq (sq (sq (sq (sq (sq (sq (sq (sq (sq (sq x))))))))))) = x := by decide")
lines.append(f"end FamilyF{p}")
lines.append(f"#print axioms FamilyF{p}.law1518\n#print axioms FamilyF{p}.not47\n#print axioms FamilyF{p}.not614\n#print axioms FamilyF{p}.not817\n#print axioms FamilyF{p}.not3862\n#print axioms FamilyF{p}.sq_cubed_not_id\n#print axioms FamilyF{p}.sq_pow12_id")
open(out, "w").write("\n".join(lines) + "\n"); print("wrote", out, "code digits:", len(str(code)))
