/-! Theorem F, member over F_5 (i = 2), 15 elements: 1518 holds, 47, 614, 817, 3862 fail, squaring has order 12.
    Generated by scripts/gen_family_lean.py from data/fifteen/family_Qi.json; a = [[1, 2, 2], [2, 1, 3], [3, 2, 4]], b = [[1, 4, 2], [3, 1, 1], [4, 3, 4]] (mod 5). Kernel `decide` only. -/
set_option maxRecDepth 200000
set_option maxHeartbeats 0
set_option exponentiation.threshold 2000
namespace FamilyF5
def n : Nat := 15
def code : Nat := 617115885666738859417993741415991414174140824729106734824230154130626491800224046123440220786076377908483383448797159180051883855109843118050592228782597342079387235004861995653732464112066963428529377914330629574221299893773146622765815642688567820359626625828045
def op (a b : Fin 15) : Fin 15 := ⟨(code / 15 ^ (a.val * 15 + b.val)) % 15, Nat.mod_lt _ (by decide)⟩
def sq (x : Fin 15) : Fin 15 := op x x
/-- x = (y ◇ y) ◇ (x ◇ (y ◇ x)) -/
theorem law1518 : ∀ x y : Fin 15, x = (op (op y y) (op x (op y x))) := by decide
/-- fails: x = x ◇ (x ◇ (x ◇ x)) -/
theorem not47 : ¬ (∀ x : Fin 15, x = (op x (op x (op x x)))) := by decide
/-- fails: x = x ◇ (x ◇ ((x ◇ x) ◇ x)) -/
theorem not614 : ¬ (∀ x : Fin 15, x = (op x (op x (op (op x x) x)))) := by decide
/-- fails: x = x ◇ ((x ◇ x) ◇ (x ◇ x)) -/
theorem not817 : ¬ (∀ x : Fin 15, x = (op x (op (op x x) (op x x)))) := by decide
/-- fails: x ◇ x = (x ◇ (x ◇ x)) ◇ x -/
theorem not3862 : ¬ (∀ x : Fin 15, (op x x) = (op (op x (op x x)) x)) := by decide
theorem sq_cubed_not_id : ¬ (∀ x : Fin 15, sq (sq (sq x)) = x) := by decide
theorem sq_pow12_id : ∀ x : Fin 15, sq (sq (sq (sq (sq (sq (sq (sq (sq (sq (sq (sq x))))))))))) = x := by decide
end FamilyF5
#print axioms FamilyF5.law1518
#print axioms FamilyF5.not47
#print axioms FamilyF5.not614
#print axioms FamilyF5.not817
#print axioms FamilyF5.not3862
#print axioms FamilyF5.sq_cubed_not_id
#print axioms FamilyF5.sq_pow12_id
