/-!
# One-generated magmas satisfying laws 1518 and 3862

For a magma `(G, op)` write `S x = op x x`.  From the two ETP laws

* 1518 : `x = (y ◇ y) ◇ (x ◇ (y ◇ x))`
* 3862 : `x ◇ x = (x ◇ (x ◇ x)) ◇ x`

we prove, for every `x`, the complete multiplication table of `T = {x, S x, S (S x)}`:
every product `u ◇ v` with `u, v ∈ T` equals `S v`, and `S (S (S x)) = x`.  Hence every word in `x` lies in `T`,
the submagma generated by `x` is `T`, and `T` has either one element or three distinct elements on which `◇` is
the cyclic shift `u ◇ v = S v`.  This is the classification of one-generated (1518 + 3862)-magmas, in core Lean,
following the equational proofs found by Vampire 5.1.0 (research/audit/atp/eq_*.proof).  No finiteness is used.
-/

namespace OneGenerated1518

variable {G : Type} (op : G → G → G)

/-- law 359, `(x ◇ x) ◇ x = x ◇ x`, from 1518 alone -/
theorem l359 (h1 : ∀ x y, x = op (op y y) (op x (op y x))) (x : G) : op (op x x) x = op x x := by
  have i := h1 x x
  have ii := h1 (op x x) x
  rw [← i] at ii
  exact ii.symm

/-- `x ◇ S x = S (S x)` -/
theorem x_A (h1 : ∀ x y, x = op (op y y) (op x (op y x))) (h2 : ∀ x, op x x = op (op x (op x x)) x) (x : G) :
    op x (op x x) = op (op x x) (op x x) := by
  have e1 := h1 (op x (op x x)) (op x x)
  have hx : op (op x x) (op x (op x x)) = x := (h1 x x).symm
  rw [hx] at e1
  have h3 : op (op x (op x x)) x = op x x := (h2 x).symm
  rw [h3] at e1
  rw [l359 op h1 (op x x)] at e1
  exact e1

/-- `x ◇ S (S x) = x` -/
theorem x_B (h1 : ∀ x y, x = op (op y y) (op x (op y x))) (h2 : ∀ x, op x x = op (op x (op x x)) x) (x : G) :
    op x (op (op x x) (op x x)) = x := by
  have a : op (op x (op x x)) x = op x x := (h2 x).symm
  have b := h1 x (op x (op x x))
  rw [a] at b
  rw [l359 op h1 (op x (op x x))] at b
  have d := l359 op h1 (op x (op x x))
  rw [← b] at d
  rw [x_A op h1 h2 x] at d
  exact d

/-- `S x ◇ S (S x) = x` -/
theorem A_B (h1 : ∀ x y, x = op (op y y) (op x (op y x))) (h2 : ∀ x, op x x = op (op x (op x x)) x) (x : G) :
    op (op x x) (op (op x x) (op x x)) = x := by
  have hx : op (op x x) (op x (op x x)) = x := (h1 x x).symm
  rw [x_A op h1 h2 x] at hx
  exact hx

/-- `S (S x) ◇ x = S x` -/
theorem B_x (h1 : ∀ x y, x = op (op y y) (op x (op y x))) (h2 : ∀ x, op x x = op (op x (op x x)) x) (x : G) :
    op (op (op x x) (op x x)) x = op x x := by
  have a : op (op x (op x x)) x = op x x := (h2 x).symm
  rw [x_A op h1 h2 x] at a
  exact a

/-- `S (S x) ◇ S (S x) = x`, i.e. `S (S (S x)) = x` -/
theorem B_B (h1 : ∀ x y, x = op (op y y) (op x (op y x))) (h2 : ∀ x, op x x = op (op x (op x x)) x) (x : G) :
    op (op (op x x) (op x x)) (op (op x x) (op x x)) = x := by
  have e := h1 x (op x x)
  rw [l359 op h1 x] at e
  rw [x_A op h1 h2 x] at e
  exact e.symm

/-- membership in `T = {x, S x, S (S x)}` -/
def inT (x y : G) : Prop := y = x ∨ y = op x x ∨ y = op (op x x) (op x x)

/-- The table: on `T`, `u ◇ v = S v = v ◇ v`. -/
theorem table (h1 : ∀ x y, x = op (op y y) (op x (op y x))) (h2 : ∀ x, op x x = op (op x (op x x)) x) (x : G) :
    ∀ u v, inT op x u → inT op x v → op u v = op v v := by
  intro u v hu hv
  -- the three diagonal cases close by `rfl` inside `rw`; six off-diagonal goals remain, in row-major order
  rcases hu with hu | hu | hu <;> rcases hv with hv | hv | hv <;> rw [hu, hv]
  · exact x_A op h1 h2 x
  · rw [x_B op h1 h2 x, B_B op h1 h2 x]
  · exact l359 op h1 x
  · rw [A_B op h1 h2 x, B_B op h1 h2 x]
  · exact B_x op h1 h2 x
  · exact l359 op h1 (op x x)

/-- `T` is closed under `◇` -/
theorem closed (h1 : ∀ x y, x = op (op y y) (op x (op y x))) (h2 : ∀ x, op x x = op (op x (op x x)) x) (x : G) :
    ∀ u v, inT op x u → inT op x v → inT op x (op u v) := by
  intro u v hu hv
  rw [table op h1 h2 x u v hu hv]
  rcases hv with hv | hv | hv <;> rw [hv]
  · exact Or.inr (Or.inl rfl)
  · exact Or.inr (Or.inr rfl)
  · exact Or.inl (B_B op h1 h2 x)

/-- words in one generator -/
inductive W where
  | v : W
  | m : W → W → W

def ev (x : G) : W → G
  | .v => x
  | .m a b => op (ev x a) (ev x b)

/-- every word in `x` evaluates into `T`: the submagma generated by `x` is `T` -/
theorem words_in_T (h1 : ∀ x y, x = op (op y y) (op x (op y x))) (h2 : ∀ x, op x x = op (op x (op x x)) x) (x : G) :
    ∀ w : W, inT op x (ev op x w) := by
  intro w
  induction w with
  | v => exact Or.inl rfl
  | m a b iha ihb => exact closed op h1 h2 x _ _ iha ihb

/-- `T` has one element or three distinct elements -/
theorem one_or_three (h1 : ∀ x y, x = op (op y y) (op x (op y x))) (h2 : ∀ x, op x x = op (op x (op x x)) x) (x : G) :
    (op x x = x ∧ op (op x x) (op x x) = x) ∨
    (op x x ≠ x ∧ op (op x x) (op x x) ≠ x ∧ op (op x x) (op x x) ≠ op x x) := by
  by_cases hA : op x x = x
  · left
    refine ⟨hA, ?_⟩
    rw [hA, hA]
  · right
    refine ⟨hA, ?_, ?_⟩
    · intro hB
      have e := B_B op h1 h2 x
      rw [hB] at e
      exact hA e
    · intro hB
      have e := B_B op h1 h2 x
      rw [hB] at e
      exact hA (hB.symm.trans e)

end OneGenerated1518

#print axioms OneGenerated1518.table
#print axioms OneGenerated1518.words_in_T
#print axioms OneGenerated1518.one_or_three
